library(dplyr)
library(tidyr)
library(readxl)
library(ggplot2)

download.file(url = "http://www.inee.edu.mx/images/stories/2016/planea/PLANEA_6prim_Resultados_de_Logro_LyC_20160125.xlsx", destfile = "PLANEA_6prim_Resultados_de_Logro_LyC_20160125.xlsx")

excel_sheets("PLANEA_6prim_Resultados_de_Logro_LyC_20160125.xlsx")

ent <-
  read_excel("PLANEA_6prim_Resultados_de_Logro_LyC_20160125.xlsx", sheet = "7", skip = 5, col_names = F) %>%
  select(ENT = X0, CAT = X1, N1 = X2, N2 = X6, N3 = X10, N4 = X14) %>%
  .[1:214,]

ent[3:6]<-
  lapply(
    ent[3:6], function(x) gsub("\\*", "", x) %>%
      as.numeric
    )

ent <-
  ent %>%
  filter(is.na(CAT)) %>%
  select(-CAT) %>%
  gather(key = NIVEL, value = PERC, N1:N4)

#----
ent %>%
  ggplot(aes(ENT, PERC)) +
  geom_bar(aes(fill = NIVEL), stat = "identity", position = "dodge") +
  geom_text(aes(label = paste(PERC, "%", sep = "")), hjust = -.2, vjust = 1) +
  geom_text(aes(label = substr(ENT, 1, 3), vjust = 0, hjust = -.2)) +
  coord_flip() +
  facet_grid(. ~ NIVEL)

ent %>%
  ggplot(aes(ENT, PERC)) +
  geom_bar(aes(fill = NIVEL), stat = "identity") +
  geom_text(aes(label = PERC), vjust = -.2) +
  geom_text(aes(label = substr(ENT, 1, 3), vjust = -1.3)) +
  facet_grid(NIVEL~.)

ent %>%
  mutate(PERC = ifelse(NIVEL == "N1", PERC * -1, PERC)) %>%
  ggplot(aes(ENT, PERC, fill = NIVEL)) +
  geom_bar(stat = "identity") +
  coord_flip()

ggplot() +
  geom_bar(
    data = ent %>%
      filter(NIVEL == "N1") %>%
      mutate(PERC = PERC * -1),
    aes(ENT, PERC, fill = NIVEL),
    stat = "identity"
  ) +
  geom_bar(
    data = ent %>% filter(NIVEL != "N1"),
    aes(ENT, PERC, fill = NIVEL),
    stat = "identity"
  ) +
  coord_flip()

#----
ggplot() +
  geom_bar(
    data = ent %>%
      filter(NIVEL == "N1") %>%
      mutate(PERC = PERC * -1
             ),
    aes(ENT, PERC, fill = NIVEL),
    stat = "identity"
    ) +
  geom_text(
    data = ent %>%
      filter(NIVEL == "N1") %>%
      mutate(PERC = PERC * -1,
             POS = 0.5 * PERC
      ),
    aes(ENT, POS,
        label = PERC %>% gsub("-", "", .) %>% paste("%", sep = "")
        )
    ) +
  geom_bar(
    data = ent %>%
      filter(NIVEL != "N1"),
    aes(ENT, PERC, fill = NIVEL),
    stat = "identity"
    ) +
  geom_text(
    data = ent %>%
      filter(NIVEL != "N1") %>%
      group_by(ENT) %>%
      mutate(POS = cumsum(PERC) - (0.5 * PERC))
    ,
    aes(ENT, POS,
        label = PERC %>% paste("%", sep = ""))
    ) +
  coord_flip() +
  scale_x_discrete(limits = rev(levels(ordered(ent$ENT)))) +
  theme(
    panel.grid.major.y = element_line(color = "#dddddd"),
    panel.grid.major.x = element_blank(),
    panel.background = element_rect(fill = "white"),
    axis.text.y = element_text(vjust = .3),
    axis.text.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "top"
    ) +
  labs(title = "Proporción de estudiantes de Sexto de Primaria por nivel de logro\n Lenguaje y Comunicación",
       y = "Porcentaje de estudiantes\n en cada nivel de logro",
       x = "Entidades") +
  scale_fill_discrete(
    name = "Nivel",
    labels = c("I", "II", "III", "IV")
    )

# ----
ent %>%
  mutate(
    LOGRO = ifelse(NIVEL %in% "N1", "BAJO", "ALTO"),
    PERC = ifelse(LOGRO == "BAJO", PERC * -1, PERC)
  ) %>%
  group_by(ENT, LOGRO) %>%
  summarise(PERC = sum(PERC)) %>%
  ggplot(aes(ENT, PERC, fill = LOGRO)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(position = position_dodge(width = 1),
    aes(
      label = as.character(PERC) %>%
        gsub("-", "", .) %>%
        paste("%", sep = "")
      )
    ) +
  coord_flip() +
  scale_x_discrete(limits = rev(levels(ordered(ent$ENT))))

#----
ent %>%
  mutate(
    LOGRO = ifelse(NIVEL %in% c("N1", "N2"), "BAJO", "ALTO")
  ) %>%
  group_by(ENT, LOGRO) %>%
  summarise(PERC = sum(PERC)) %>%
  mutate(
    POS = cumsum(PERC) - (0.5 * PERC)
  ) %>%
  ggplot(aes(ENT, PERC, fill = LOGRO)) +
  geom_bar(stat = "identity") +
  geom_text(aes(ENT, POS, label = PERC)) +
  coord_flip() +
  scale_x_discrete(limits = rev(levels(ordered(ent$ENT))))

#----
ent_nac <- read_excel("PLANEA_6prim_Resultados_de_Logro_LyC_20160125.xlsx", sheet = "3", skip = 5, col_names = F) %>% select(ENT = X0, CAT = X2, NV3 = X23) %>% .[1:8, ]

ent_nac$NV3 <- gsub("(\\*)", "", ent_nac$NV3) %>% as.numeric()

ent_nac[1,2] <- "GENERAL"

ent_nac$CAT[ent_nac$CAT == "Baja y Muy baja"] <- "BAJA"
ent_nac$CAT[ent_nac$CAT == "Muy alta y Alta"] <- "ALTA"

ent_nac <- ent_nac %>% filter(CAT %in% c("GENERAL", "BAJA", "ALTA"))

ent_nac <-
  ent_nac %>%
  fill(ENT) %>%
  spread(CAT, NV3) %>%
  mutate(DIF = BAJA -ALTA)

ent <-
  bind_rows(
    ent_nac,
    ent
  )

rm(ent_nac)

ent %>%
  mutate(ROJO = ifelse(ENT == "Nacional", "SI", NA)) %>%
  ggplot(aes(DIF, GENERAL)) +
  geom_point(aes(color = ROJO), show.legend = FALSE) +
  geom_text(aes(label = ENT, color = ROJO), vjust = -1, show.legend = FALSE) +
  scale_x_continuous(limits = c(0, 30), expand = c(0, 0)) +
  scale_y_continuous(limits = c(12, 30), expand = c(0,0)) +
  theme_bw()
